### ISSUE TITLE
adding: #define STICKBREAKER

### ISSUE THREAD

**Issue by everslick** [stickbreaker/arduino-esp32#17]
I have to regularly switch between the origin:master and your fork, but the I2C API is incompatible. would you mind sneaking in a ```#define STICKBREAKER``` in Wire.h so I can automagically switch between code branches? This is only required until your changes are merged upstream of course. or is there another way to detect the API version?

**Comment by stickbreaker** [comment]
@everslick thats fine, I'm cleaning up the current code and adding support for the second hardware I2C. 

Chuck.

**Comment by stickbreaker** [comment]
Done
