### ISSUE TITLE
I2C compile error when CONFIG_DISABLE_HAL_LOCKS defined

### ISSUE THREAD

**Issue by viordash** [stickbreaker/arduino-esp32#20]
Hi!
The method "\esp32-hal-i2c.c -> void i2cDumpI2c(i2c_t * i2c)" has the line:
log_e("lock=%p",i2c->lock);
but declaration of field "lock" is under CONFIG_DISABLE_HAL_LOCKS defines.
And in case of using a CONFIG_DISABLE_HAL_LOCKS, compilation causes an error.

**Comment by stickbreaker** [comment]
@viordash Sorry about that, I don't use this Arduino code as a component under IDF.  I'll add a conditional compile to remove that incompatibility

Chuck.

**Comment by stickbreaker** [comment]
@viordash All done!
