### ISSUE TITLE
Continue with this forks changes or main?

### ISSUE THREAD

**Issue by chinswain** [stickbreaker/arduino-esp32#33]
Hi Chuck, I noticed you've been updating the main repository - should we be overlaying the i2c files from here or can we just use the main now?

**Comment by stickbreaker** [comment]
@chinswain the main branch espressif/arduino has a staging branch stickbreaker-i2c, it will be the one merged. me-no-dev and I have discussed how to add multi thread capability.  I don't know if the merge is delayed pending multi thread, or just out of caution. 

I will be working on Slave mode in this repo.

I would recommend you try the stickbreaker-i2c branch, maybe some success reports in espressif/arduino will accelerate the merge?

The 'main' espressif/arduino still has the unreliable polling i2c.  You have to select the 'stickbreaker-i2c' branch.

I don't understand the resistance to merging my ISR version.
 
Chuck.

**Comment by me-no-dev** [comment]
The only reason why it's not merged is that API might change a bit, so I do not want to merge something that will have major change. But soon it will be in Master ;)

**Comment by chinswain** [comment]
I'll close this now - @stickbreaker has said the changes are now merged.
