### ISSUE TITLE
Compilation Warning with 2 of July version

### ISSUE THREAD

**Issue by rrobinet** [stickbreaker/arduino-esp32#40]
**Hardware:**

Board: ESP32 WEMOS LOLIN32 WROOM
Core Installation/update date: 11/jan/2017 (last version from Github
IDE name: Arduino IDE
Flash Frequency: ?40Mhz?
Upload Speed: ?115200?
### Description:
Describe your problem here
@stickbreaker 
I still have random issue with the wire library (currently using your patched version of the 13 of March) 
So I did reinstall your complete save set of the 2nd of July, that looks OK for the time being.
However I have some compilation errors (something I had in the past but was solved by reinstalling the software) and  I am wondering if this is due to my set-up or if this a general one.

Arduino/Sketch/hardware/espressif/esp32/cores/esp32/esp32-hal-i2c.c: In function 'i2cInit':
Arduino/Sketch/hardware/espressif/esp32/cores/esp32/esp32-hal-i2c.c:329:5: warning: implicit declaration of function 'i2cReleaseISR' [-Wimplicit-function-declaration]
     i2cReleaseISR(i2c); // ISR exists, release it before disabling hardware
     ^
Arduino/Sketch/hardware/espressif/esp32/cores/esp32/esp32-hal-i2c.c: At top level:
Arduino/Sketch/hardware/espressif/esp32/cores/esp32/esp32-hal-i2c.c:1242:6: warning: conflicting types for 'i2cReleaseISR'
 void i2cReleaseISR(i2c_t * i2c){
      ^
Arduino/Sketch/hardware/espressif/esp32/cores/esp32/esp32-hal-i2c.c:329:5: note: previous implicit declaration of 'i2cReleaseISR' was here
     i2cReleaseISR(i2c); // ISR exists, release it before disabling hardware

Thanks in advance Robert

**Comment by stickbreaker** [comment]
@rrobinet Ya, that warning is due to out of ordering of the functions `i2cReleaseISR()` is defined in line 1242 but first used in line 329.

I'm working on some changes, I'll fix that when I apply my update.

Chuck.

**Comment by rrobinet** [comment]
@stickbreaker 
Chuck,
The problem is actually the fact that `void i2cReleaseISR(i2c_t * i2c)`is not defined in the `esp32-hal-i2c.h `file.
I did apply this change and there are no error anymore
Robert
