### ISSUE TITLE
i2c communications on ESP32

### ISSUE THREAD

**Issue by ChuckVanzant** [stickbreaker/arduino-esp32#42]
I was reading your description of the issues of i2c communications on ESP32. You obviously have studied this issue in great detail, I am trying to better understand what is necessary when using i2c on an ESP32. I am fairly new to this lower level programming and thought that maybe you could answer a couple of questions.

You indicate that traditionally on Arduino, and for example your Adafruit_SI7021 code, that you 

"set internal address pointer in I2C EEPROM from which to read", 
then call
uint8_t err =Wire.endTransmission(false); // don't send a STOP, just Pause I2C operations

Is it really necessary to keep the connection active via the "false" argument before the call to Wire.requestFrom()?

I understand that if Wire.endTransmission(false) is called, then I2C_ERROR_CONTINUE must be an acceptable return value for the ESP32.

I have a modified a version of Adafruit_SI7021 where I replaced Wire.endTransmission(false) with Wire.endTransmission(), which now returns I2C_ERROR_OK (0) instead of I2C_ERROR_CONTINUE (7) and the sensor appears to return valid data as desired assuming I accept I2C_ERROR_OK as an acceptable value for the ESP32.

I've tested this on ESP32, ESP8266, and ATmega328 devices without any detected problems. Maybe there are issues that are not obvious.

What am I missing that would require the connection to remain active between Wire.endTransmission
and Wire.requestFrom? I see other areas of code where that does not occur.

Thanks in advance for any enlightenment you can provide! :)

**Comment by stickbreaker** [comment]
@ChuckVanzant The ReSTART operation (`Wire.endTransmission(false)`) is required by some hardware. I know the MMA8451 accellerometer requires it.  When reading a specific register I have to use it, with this sensor, if `Wire.endtransmission()` is used, the internal register pointer goes back to zero.  So, If i want to read register 0x21:
```c++
Wire.beginTransmission(0x3A);
Wire.write(0x21);
Wire.endTransmission();
Wire.requestFrom(0x3A, 1);
```
will read the data in register 0.

Most i2c devices don't have this behavior. On the ones that do, with the ESP32 you will have to change your error detection. 

The Arduino breaks i2c protocol when it allows bare ReSTARTs.

`I2C_ERROR_OK` translates to 0 just like Arduino, `I2C_ERROR_CONTINUE` is a new error code specific to ESP32.


Chuck.
